Migrate xpallet-asset-registrar to pallet v2
chainx-org/ChainX pull request #550
Opened 2021-06-10 05:18 UTC by VegeBun-csj

![image](https://user-images.githubusercontent.com/39252213/121468940-3693fe00-c9ee-11eb-9d36-e3637291da49.png)

2021-06-10 08:13 UTC, VegeBun-csj commented
### pass all the tests
![image](https://user-images.githubusercontent.com/39252213/121489295-8a124600-ca06-11eb-80e7-77c0a292c181.png)

2021-06-10 08:36 UTC, liuchengxu commented on xpallets/assets-registrar/src/lib.rs
> +    /// Asset id list for each Chain.
```suggestion
    /// Asset id list for each Chain.
    #[pallet::storage]
    #[pallet::getter(fn asset_ids_of)]
```

2021-06-10 08:37 UTC, liuchengxu requested changes
Merge the latest develop branch and then make the CI passes.

2021-06-12 05:25 UTC, hacpy reviewed
It is recommended to rearrange the order of pallet components in the following order:
- pallet::config
- pallet::pallet
- pallet::call
- pallet::event
- pallet::error
- pallet::storage

2021-06-12 12:26 UTC, merged