update transaction fee xpallet
chainx-org/ChainX pull request #561
Opened 2021-06-15 11:12 UTC by rain-9811

2021-06-16 08:16 UTC, liuchengxu commented on xpallets/transaction-fee/src/types.rs
> +    pub partial_details: pallet_transaction_payment::FeeDetails<Balance>,
Make the name a little shorter?

```suggestion
    pub base: pallet_transaction_payment::FeeDetails<Balance>,
```

2021-06-16 08:19 UTC, liuchengxu requested changes
Please delete all the useless lines.

For the call having extra fee, have you tested locally that `xfee_queryDetails` works exactly like before?

2021-06-17 03:51 UTC, liuchengxu requested changes
The previous copy-pasted code should be removed, e.g., `compute_fee_raw()`.

2021-06-17 04:00 UTC, rain-9811 commented
The transaction fee result is the same like before , the updated pallet result is 
![image](https://user-images.githubusercontent.com/71935454/122329192-909f4100-cf63-11eb-8037-762f2497bd11.png)
while the partial pallet result is
![image](https://user-images.githubusercontent.com/71935454/122329242-9eed5d00-cf63-11eb-9407-a81ee0094d46.png)

2021-06-17 08:50 UTC, alannotnerd commented
Close #442

2021-06-17 09:16 UTC, alannotnerd commented on xpallets/transaction-fee/src/types.rs
> +    pub base: pallet_transaction_payment::FeeDetails<Balance>,
Don't modify rpc return type structure

2021-06-17 09:17 UTC, alannotnerd commented on xpallets/transaction-fee/src/lib.rs
> +    //decl_event, decl_module, pallet,
Remove comment

2021-06-18 03:42 UTC, rjman-ljm reviewed
The rest is LGTM

2021-06-18 03:42 UTC, rjman-ljm commented on xpallets/transaction-fee/src/lib.rs
> +    impl<T: Config> Pallet<T> {}
delete it, it's unnecessary

2021-06-18 03:42 UTC, rjman-ljm commented on xpallets/transaction-fee/rpc/src/lib.rs
> +                    }
```suggestion
                inclusion_fee: fee_details.inclusion_fee.map(|fee| InclusionFee {
                    base_fee: fee.base_fee.into(),
                    len_fee: fee.len_fee.into(),
                    adjusted_weight_fee: fee.adjusted_weight_fee.into()
                }),
```

2021-06-18 03:42 UTC, rjman-ljm commented on xpallets/transaction-fee/rpc/src/lib.rs
> +                    }
If you import `pallet_transaction_payment::InclusionFee` in the header, you don't have to change it here (I think it would be better)

2021-06-18 03:42 UTC, rjman-ljm commented on xpallets/transaction-fee/rpc/src/lib.rs
> +use xpallet_transaction_fee_rpc_runtime_api::FeeDetails;
```suggestion
use xpallet_transaction_fee_rpc_runtime_api::FeeDetails;
use pallet_transaction_payment::InclusionFee;
```

2021-06-18 03:42 UTC, rjman-ljm commented on xpallets/transaction-fee/src/lib.rs
>  type BalanceOf<T> = <<T as pallet_transaction_payment::Config>::OnChargeTransaction as pallet_transaction_payment::OnChargeTransaction<T>>::Balance;
```suggestion
type BalanceOf<T> = 
    <<T as pallet_transaction_payment::Config>::OnChargeTransaction as pallet_transaction_payment::OnChargeTransaction<T>>::Balance;
```

2021-06-18 03:42 UTC, rjman-ljm commented on xpallets/transaction-fee/src/lib.rs
![header](https://cdn.jsdelivr.net/gh/rjman-ljm/resources@master/assets/1623987692255-1623987692252.png)
You finish the work, it should be deleted or modified.

2021-06-18 03:44 UTC, rjman-ljm reviewed
the rest is LGTM

2021-06-18 09:50 UTC, alannotnerd commented on xpallets/transaction-fee/rpc/runtime-api/src/lib.rs
> +// //! Runtime API definition for transaction fee module.
Remove duplicated slash

2021-06-18 09:55 UTC, alannotnerd commented on runtime/dev/src/lib.rs
> +                final_fee: total + extra_fee,
Format code

2021-06-23 07:04 UTC, merged